### ISSUE TITLE
数据项1个的时候有点问题。

### ISSUE THREAD

**Issue by Basakerone** [genius158/simplebanner#1]
当数量为1个的时候就不对了，看了一下代码 。
   if (dataSourceSize >= 2) {
            mDataSource.add(data.get(dataSourceSize - 1));
            mDataSource.addAll(data);
            mDataSource.add(data.get(0));
        } else {  // 添加了两个数据项。。。造成循环失败（话说1个还循环什么。。。）。
            mDataSource.add(data.get(0));
            mDataSource.add(data.get(0));
        }
 我这边改成了一个不循环，也不显示Indicator，非常感谢作者提供这么好的库。

**Comment by genius158** [comment]
嗯，这个没注意
